steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/api-gateway:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '--cache-from', 'gcr.io/$PROJECT_ID/api-gateway:latest',
          '-t', 'gcr.io/$PROJECT_ID/api-gateway:latest', 
          '-f', 'devops/Dockerfile', 
          '.'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/api-gateway:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ["printf '{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"%s\"}}}}}' `date +%s` | xargs -0 kubectl patch deployment api-gateway -p"]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
images: ['gcr.io/$PROJECT_ID/api-gateway:latest']
