steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/api-gateway:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '--cache-from', 'gcr.io/$PROJECT_ID/api-gateway:latest',
          '-t', 'gcr.io/$PROJECT_ID/api-gateway:latest', 
          '-f', 'devops/Dockerfile', 
          '.'
        ]
images: ['gcr.io/$PROJECT_ID/api-gateway:latest']
